[common]
variables = ["module_name", "add_gin"]

[variables]
[variables.module_name]
message = "Your module name:"
type = "input"
meta = ["github.com/cqroot/go-template"]

[variables.add_gin]
message = "Add gin?"
type = "toggle"
meta = ["Yes", "No"]

[include_path_rules]
"internal/server" = ["add_gin==Yes"]
"internal/middleware" = ["add_gin==Yes"]

[scripts]
after = ["scripts/init.sh"]
